# Generated by Django 5.2.1 on 2025-06-02 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variations',
            options={'verbose_name': 'Variations', 'verbose_name_plural': 'Variations'},
        ),
        migrations.AlterField(
            model_name='variations',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation', to='store.product'),
        ),
    ]
