# Generated by Django 5.2.1 on 2025-06-02 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variations_options_alter_variations_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_set', to='store.product'),
        ),
    ]
