# Generated by Django 5.2.1 on 2025-05-31 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='Date_joined',
            new_name='date_joined',
        ),
    ]
