# Generated by Django 5.2.1 on 2025-06-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_date_joined_accounts_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
