# Generated by Django 5.2.1 on 2025-06-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_created_at'),
        ('store', '0004_alter_variations_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oderproduct',
            name='size',
        ),
        migrations.RemoveField(
            model_name='oderproduct',
            name='variation',
        ),
        migrations.AddField(
            model_name='oderproduct',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variations'),
        ),
    ]
