# Generated by Django 5.2.1 on 2025-06-12 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_oderproduct_size_remove_oderproduct_variation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oderproduct',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
